runtime: python311

env_variables:
  CLOUD_SQL_CONNECTION_NAME: 'total-handler-244211:us-central1:saas'
  DB_NAME: 'saas1'
  DB_USER: 'saas1'
  DB_PASSWORD: 'yoshi2003'
  GAE_ENV: 'standard'

handlers:
- url: /assets/.*\.(js|css)
  static_files: dist/assets/\0
  upload: dist/assets/.*\.(js|css)$
  expiration: "0s"
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"

- url: /(.*\.(html|png|jpg|jpeg|gif|svg))
  static_files: dist/\1
  upload: dist/.*\.(html|png|jpg|jpeg|gif|svg)$
  expiration: "1h"

- url: /.*
  script: auto
