#!/bin/bash
# Xserver デプロイ用コマンド集

echo "========================================"
echo "Xserver デプロイコマンド"
echo "========================================"
echo ""
echo "1. SSH接続:"
echo "   ssh yoshifumik@sv14067.xserver.jp -p 10022"
echo ""
echo "2. 接続後のディレクトリ移動:"
echo "   cd ~/gta-test1.com/public_html/myapp"
echo ""
echo "3. ディレクトリ作成（初回のみ）:"
echo "   mkdir -p ~/gta-test1.com/public_html/myapp"
echo "   mkdir -p ~/gta-test1.com/public_html/myapp/static"
echo "   mkdir -p ~/gta-test1.com/public_html/myapp/templates"
echo ""
echo "4. ファイルアップロード（ローカルから実行）:"
echo "   # PHPファイル"
echo "   scp -P 10022 xserver_*.php yoshifumik@sv14067.xserver.jp:~/gta-test1.com/public_html/myapp/"
echo ""
echo "   # Pythonアプリケーション"
echo "   scp -P 10022 main_xserver.py yoshifumik@sv14067.xserver.jp:~/gta-test1.com/public_html/myapp/"
echo "   scp -P 10022 .env.xserver yoshifumik@sv14067.xserver.jp:~/gta-test1.com/public_html/myapp/.env"
echo ""
echo "   # 静的ファイル"
echo "   scp -P 10022 -r static/* yoshifumik@sv14067.xserver.jp:~/gta-test1.com/public_html/myapp/static/"
echo "   scp -P 10022 -r templates/* yoshifumik@sv14067.xserver.jp:~/gta-test1.com/public_html/myapp/templates/"
echo ""
echo "5. パーミッション設定（SSH接続後）:"
echo "   chmod 755 ~/gta-test1.com/public_html/myapp"
echo "   chmod 644 ~/gta-test1.com/public_html/myapp/*.php"
echo "   chmod 644 ~/gta-test1.com/public_html/myapp/.env"
echo ""
echo "6. アクセスURL:"
echo "   https://gta-test1.com/myapp/xserver_test_web.php"
echo "   https://gta-test1.com/myapp/xserver_create_tables_web.php"
echo "   https://gta-test1.com/myapp/xserver_data_test.php"
echo ""
echo "========================================"